/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CodeLineProps {
  content: string;
  indentation: number;
  lineNumber: number;
}

const CodeLine: React.FC<CodeLineProps> = ({
  content,
  indentation,
  lineNumber,
}) => {
  return (
    <div className="flex gap-0 pr-20 pl-5  !border-0 max-md:flex-wrap max-md:pr-5">
      <div className="text-zinc-500 w-8 text-right pr-2">{lineNumber}</div>
      <div
        className={`flex gap-1.5 self-start py-0.5 text-gray-200 whitespace-nowrap max-md:px-5 ml-${
          indentation * 4
        }`}
      >
        {content}
      </div>
    </div>
  );
};

export default CodeLine;
