/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FileHeaderProps {
  title: string;
  fileIcon: string;
  avatarSrc: string;
}

const FileHeader: React.FC<FileHeaderProps> = ({
  title,
  fileIcon,
  avatarSrc,
}) => {
  return (
    <header className="flex gap-5 justify-between px-4 py-2 w-full whitespace-nowrap bg-black rounded-md bg-blend-normal text-neutral-400 max-md:flex-wrap max-md:max-w-full min-w-[400px]">
      <div className="flex gap-2 my-auto">
       <ReactIcon />
        <div className="my-auto">{title}</div>
      </div>
      <ClipboardIcon />
    </header>
  );
};

export default FileHeader;

function ClipboardIcon() {
  return (


<svg width="33" height="33" viewBox="0 0 33 33" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.6354 20.8027C10.7149 20.8027 9.96875 20.0565 9.96875 19.136V10.8027C9.96875 9.88218 10.7149 9.13599 11.6354 9.13599H17.4687C18.0857 9.13599 18.6242 9.47115 18.9124 9.96932M15.8021 24.136H21.6354C22.5559 24.136 23.3021 23.3898 23.3021 22.4693V14.136C23.3021 13.2155 22.5559 12.4693 21.6354 12.4693H15.8021C14.8816 12.4693 14.1354 13.2155 14.1354 14.136V22.4693C14.1354 23.3898 14.8816 24.136 15.8021 24.136Z" stroke="#A1A1A1" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

  )
}

function ReactIcon() {
  return (
    <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g clip-path="url(#clip0_16_20)">
    <path d="M8.83551 10.0619C9.62312 10.0619 10.2616 9.42341 10.2616 8.6358C10.2616 7.8482 9.62312 7.20972 8.83551 7.20972C8.0479 7.20972 7.40942 7.8482 7.40942 8.6358C7.40942 9.42341 8.0479 10.0619 8.83551 10.0619Z" fill="#A1A1A1"/>
    <path d="M8.83552 11.5573C13.0617 11.5573 16.4877 10.2492 16.4877 8.63561C16.4877 7.02197 13.0617 5.71387 8.83552 5.71387C4.60934 5.71387 1.18335 7.02197 1.18335 8.63561C1.18335 10.2492 4.60934 11.5573 8.83552 11.5573Z" stroke="#A1A1A1" stroke-width="0.695652"/>
    <path d="M6.30528 10.0966C8.41837 13.7565 11.2642 16.0695 12.6617 15.2627C14.0591 14.4559 13.479 10.8348 11.3659 7.17483C9.25279 3.51485 6.40694 1.20191 5.0095 2.00872C3.61205 2.81554 4.19219 6.43659 6.30528 10.0966Z" stroke="#A1A1A1" stroke-width="0.695652"/>
    <path d="M6.30521 7.17472C4.19212 10.8347 3.61198 14.4557 5.00942 15.2626C6.40687 16.0694 9.25272 13.7564 11.3658 10.0965C13.4789 6.43648 14.059 2.81543 12.6616 2.00861C11.2641 1.2018 8.4183 3.51474 6.30521 7.17472Z" stroke="#A1A1A1" stroke-width="0.695652"/>
    </g>
    <defs>
    <clipPath id="clip0_16_20">
    <rect width="16" height="16" fill="white" transform="translate(0.835449 0.635742)"/>
    </clipPath>
    </defs>
    </svg>
    )
}