/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ActivityItemProps {
  imageUrl: string;
  content: React.ReactNode;
  time: string;
}

const ActivityItem: React.FC<ActivityItemProps> = ({
  imageUrl,
  content,
  time,
}) => {
  return (
    <div className="flex gap-3 items-center py-3 tracking-normal bg-blend-normal">
      <img
        loading="lazy"
        src={imageUrl}
        className="shrink-0 self-stretch my-auto w-8 border border-solid bg-blend-normal aspect-square border-zinc-800 rounded-[50px]"
        alt=""
      />
      <div className="flex-auto self-stretch my-auto text-white">{content}</div>
      <div className="self-stretch my-auto text-stone-500">{time}</div>
    </div>
  );
};

export default ActivityItem;
