/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex flex-col bg-black bg-blend-normal">
      <Header />
      <main className="flex flex-col items-center px-16 pt-px pb-9 -mt-9 w-full bg-blend-normal bg-neutral-900 max-md:px-5 max-md:max-w-full">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
